/**
 * 
 */
app.controller('contentCateController',function($scope,$controller,contentCateService){
	$controller('baseController',{$scope:$scope});
	$scope.searchEntity={};
	$scope.contentList={};
	$scope.entity={};
	$scope.search=function(page,rows){
		contentCateService.search(page,rows,$scope.searchEntity).success(
				function(a){
					$scope.list=a.rows;	
					$scope.paginationConf.totalItems=a.total;
				});	
		}
	$scope.save=function(){
		contentCateService.add($scope.entity).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
	$scope.show=function(id){
		contentCateService.show(id).success(function(a){
				$scope.entity=a;
		})
	}
	$scope.del=function(){
		contentCateService.del($scope.ids).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
	$scope.updateStatus1=function(){
		contentCateService.updateStatus1($scope.ids).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
	$scope.updateStatus2=function(){
		contentCateService.updateStatus2($scope.ids).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
})