/**
 * 
 */
app.controller('contentController',function($scope,$controller,contentService){
	$controller('baseController',{$scope:$scope});
	$scope.searchEntity={};
	$scope.contentList={};
	$scope.entity={};
	$scope.search=function(page,rows){
		contentService.search(page,rows,$scope.searchEntity).success(
				function(a){
					$scope.list=a.rows;	
					$scope.paginationConf.totalItems=a.total;
				});	
		}
	$scope.findAll=function(){
		contentService.findAll().success(function(a){
			console.log(a)
			$scope.contentList=a;
		})
	}
	$scope.upload=function(){
		contentService.upload().success(function(a){
			$scope.entity.pic=a.message;
		})
	}
	$scope.save=function(){
		contentService.add($scope.entity).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
	$scope.show=function(id){
		contentService.show(id).success(function(a){
				$scope.entity=a;
		})
	}
	$scope.del=function(){
		contentService.del($scope.ids).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
	$scope.updateStatus1=function(){
		contentService.updateStatus1($scope.ids).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
	$scope.updateStatus2=function(){
		contentService.updateStatus2($scope.ids).success(function(a){
			if(a.flag){
				$scope.reloadList();
			}
		})
	}
})