/**
 * 
 */
app.controller('itemCatController',function($scope,$controller,itemCatService){
	$controller('baseController',{$scope:$scope});
	$scope.parentId=0;
	$scope.findByParentId=function(parentId){
		$scope.parentId=parentId;
		itemCatService.findByParentId(parentId).success(function(a){
			$scope.list=a;
		});
	}
	$scope.grade=1;
	$scope.setGrade=function(count){
		$scope.grade=count;
	}	   
	$scope.seletList=function(p_entity){
		if($scope.grade==1){
			$scope.entity_1=null;
			$scope.entity_2=null;
		}
		if($scope.grade==2){
			$scope.entity_1=p_entity;
			$scope.entity_2=null;
		}
		if($scope.grade==3){
			$scope.entity_2=p_entity;
		}
		console.log(p_entity)
		$scope.findByParentId(p_entity.id);
	}
	$scope.save=function(){
		itemCatService.add($scope.entity).success(function(a){
			if(a){
				$scope.findByParentId($scope.parentId);
			}
		})
	}
	$scope.show=function(id){
		itemCatService.show(id).success(function(a){
			$scope.entity=a;
		})
	}
	$scope.del=function(){
		console.log($scope.ids)
		itemCatService.del($scope.ids).success(function(a){
			if(a){
				$scope.findByParentId($scope.parentId);
			}
		})
	}
})